import {
  FaAnchor, FaAppStoreIos, FaAmazon, FaAndroid, FaApple, FaAt, FaAtom, FaAws,
  FaBasketball, FaBehance, FaBitbucket, FaBitcoin, FaBolt, FaBook, FaBookmark,
  FaBrain, FaBriefcase, FaBuilding, FaBullhorn, FaCalculator, FaCalendarDays,
  FaCamera, FaCartShopping, FaChartLine, FaChartPie, FaChess, FaCircleInfo,
  FaCircleQuestion, FaClock, FaCloud, FaCode, FaComments, FaCompass, FaCreditCard,
  FaCrown, FaDatabase, FaDev, FaDice, FaDiscord, FaDocker, FaDownload, FaDribbble,
  FaDrum, FaDumbbell, FaEthereum, FaEtsy, FaFacebookF, FaFeather, FaFigma,
  FaFileLines, FaFilm, FaFire, FaFlask, FaFlickr, FaFutbol, FaGamepad, FaGear,
  FaGem, FaGhost, FaGift, FaGithub, FaGitlab, FaGlobe, FaGoogle, FaGooglePlay,
  FaGraduationCap, FaGuitar, FaHandshake, FaHeadphones, FaHeart, FaHouse, FaImage,
  FaInbox, FaInstagram, FaItchIo, FaJs, FaKey, FaKickstarter, FaLaptop,
  FaLightbulb, FaLink, FaLinkedinIn, FaLocationDot, FaLock, FaMapLocationDot,
  FaMastodon, FaMedal, FaMedium, FaMicrophone, FaMicroscope, FaMobile, FaMoneyBill,
  FaMountain, FaMugHot, FaMusic, FaNewspaper, FaNodeJs, FaNpm, FaPalette,
  FaPaperPlane, FaPatreon, FaPaypal, FaPenNib, FaPhone, FaPinterest, FaPlane,
  FaPodcast, FaPuzzlePiece, FaPython, FaQrcode, FaRadio, FaReact, FaReddit,
  FaRobot, FaRocket, FaRss, FaSeedling, FaServer, FaShareNodes, FaShopify, FaSlack,
  FaSnapchat, FaSoundcloud, FaSpotify, FaSquarespace, FaStackOverflow, FaStar,
  FaSteam, FaStore, FaSuitcase, FaTag, FaTelegram, FaTerminal, FaThreads,
  FaThumbsUp, FaTiktok, FaTrello, FaTrophy, FaTumblr, FaTv, FaTwitch, FaUnity,
  FaUser, FaUtensils, FaVideo, FaVimeo, FaWallet, FaWhatsapp, FaWordpress,
  FaXTwitter, FaYoutube,
} from "react-icons/fa6";
import {
  SiArtstation, SiAudible, SiBandcamp, SiBilibili, SiBluesky, SiBuymeacoffee,
  SiCalendly, SiCanva, SiCashapp, SiChessdotcom, SiCodepen, SiCodewars,
  SiCoursera, SiDeviantart, SiDuolingo, SiEpicgames, SiFramer, SiFreecodecamp,
  SiGenius, SiGhost, SiGoodreads, SiGooglescholar, SiGumroad, SiHashnode,
  SiHuggingface, SiIndiehackers, SiJira, SiKaggle, SiKofi, SiLastdotfm,
  SiLeetcode, SiLetterboxd, SiLichess, SiLine, SiLinktree, SiLoom, SiNetlify,
  SiNintendoswitch, SiNotion, SiObsidian, SiPandora, SiPlaystation, SiProducthunt,
  SiReplit, SiRoblox, SiRumble, SiSignal, SiStrava, SiSubstack, SiTidal, SiUdemy,
  SiUnsplash, SiVenmo, SiVercel, SiVk, SiWebflow, SiWechat, SiZoom,
} from "react-icons/si";
import { TbMailFilled } from "react-icons/tb";
import type { IconType } from "react-icons";
import type { LinkIcon } from "./icon-names";

export type IconGroup =
  | "General"
  | "Social"
  | "Video & audio"
  | "Writing"
  | "Dev"
  | "Design"
  | "Money"
  | "Gaming";

export type IconMeta = {
  Icon: IconType;
  group: IconGroup;
  /** Extra search terms, including Spanish, so the picker finds things by intent. */
  keywords?: string;
};

/**
 * Shared by the public page and the admin picker so previews always match.
 * Typed against LinkIcon: a name in icon-names.ts with no entry here (or an
 * entry here that isn't a valid name) fails the build.
 */
export const ICON_META: Record<LinkIcon, IconMeta> = {
  // General
  link: { Icon: FaLink, group: "General", keywords: "url enlace" },
  globe: { Icon: FaGlobe, group: "General", keywords: "web site sitio mundo" },
  cv: { Icon: FaSuitcase, group: "General", keywords: "resume curriculum trabajo" },
  email: { Icon: TbMailFilled, group: "General", keywords: "mail correo contacto" },
  at: { Icon: FaAt, group: "General", keywords: "arroba mail" },
  "paper-plane": { Icon: FaPaperPlane, group: "General", keywords: "send enviar" },
  inbox: { Icon: FaInbox, group: "General", keywords: "bandeja" },
  phone: { Icon: FaPhone, group: "General", keywords: "call telefono llamar" },
  calendar: { Icon: FaCalendarDays, group: "General", keywords: "date agenda fecha" },
  clock: { Icon: FaClock, group: "General", keywords: "time hora reloj" },
  download: { Icon: FaDownload, group: "General", keywords: "descargar bajar" },
  file: { Icon: FaFileLines, group: "General", keywords: "doc pdf archivo" },
  book: { Icon: FaBook, group: "General", keywords: "libro leer" },
  bookmark: { Icon: FaBookmark, group: "General", keywords: "marcador guardar" },
  newspaper: { Icon: FaNewspaper, group: "General", keywords: "news blog noticias" },
  pen: { Icon: FaPenNib, group: "General", keywords: "write escribir pluma" },
  rocket: { Icon: FaRocket, group: "General", keywords: "launch cohete proyecto" },
  chart: { Icon: FaChartLine, group: "General", keywords: "stats grafico datos" },
  "chart-pie": { Icon: FaChartPie, group: "General", keywords: "stats torta" },
  store: { Icon: FaStore, group: "General", keywords: "shop tienda" },
  cart: { Icon: FaCartShopping, group: "General", keywords: "shop carrito comprar" },
  money: { Icon: FaMoneyBill, group: "General", keywords: "cash dinero plata" },
  "credit-card": { Icon: FaCreditCard, group: "General", keywords: "pago tarjeta" },
  wallet: { Icon: FaWallet, group: "General", keywords: "billetera" },
  tag: { Icon: FaTag, group: "General", keywords: "price etiqueta" },
  gift: { Icon: FaGift, group: "General", keywords: "regalo" },
  heart: { Icon: FaHeart, group: "General", keywords: "love corazon" },
  star: { Icon: FaStar, group: "General", keywords: "estrella favorito" },
  "thumbs-up": { Icon: FaThumbsUp, group: "General", keywords: "like pulgar" },
  crown: { Icon: FaCrown, group: "General", keywords: "corona rey" },
  gem: { Icon: FaGem, group: "General", keywords: "diamante joya" },
  medal: { Icon: FaMedal, group: "General", keywords: "medalla premio" },
  trophy: { Icon: FaTrophy, group: "General", keywords: "trofeo ganar" },
  handshake: { Icon: FaHandshake, group: "General", keywords: "deal acuerdo" },
  lightbulb: { Icon: FaLightbulb, group: "General", keywords: "idea luz" },
  bolt: { Icon: FaBolt, group: "General", keywords: "rayo fast" },
  fire: { Icon: FaFire, group: "General", keywords: "fuego hot" },
  leaf: { Icon: FaSeedling, group: "General", keywords: "planta eco verde" },
  mountain: { Icon: FaMountain, group: "General", keywords: "montaña" },
  compass: { Icon: FaCompass, group: "General", keywords: "brujula" },
  anchor: { Icon: FaAnchor, group: "General", keywords: "ancla" },
  feather: { Icon: FaFeather, group: "General", keywords: "pluma" },
  ghost: { Icon: FaGhost, group: "General", keywords: "fantasma" },
  robot: { Icon: FaRobot, group: "General", keywords: "bot ia ai" },
  brain: { Icon: FaBrain, group: "General", keywords: "cerebro ai" },
  flask: { Icon: FaFlask, group: "General", keywords: "lab quimica" },
  atom: { Icon: FaAtom, group: "General", keywords: "fisica atomo" },
  microscope: { Icon: FaMicroscope, group: "General", keywords: "ciencia" },
  calculator: { Icon: FaCalculator, group: "General", keywords: "math calcular" },
  puzzle: { Icon: FaPuzzlePiece, group: "General", keywords: "rompecabezas" },
  map: { Icon: FaMapLocationDot, group: "General", keywords: "mapa donde" },
  location: { Icon: FaLocationDot, group: "General", keywords: "pin ubicacion" },
  house: { Icon: FaHouse, group: "General", keywords: "home casa inicio" },
  building: { Icon: FaBuilding, group: "General", keywords: "office empresa" },
  briefcase: { Icon: FaBriefcase, group: "General", keywords: "work trabajo" },
  graduation: { Icon: FaGraduationCap, group: "General", keywords: "uni estudio facultad" },
  user: { Icon: FaUser, group: "General", keywords: "perfil persona about" },
  comments: { Icon: FaComments, group: "General", keywords: "chat mensajes" },
  bullhorn: { Icon: FaBullhorn, group: "General", keywords: "anuncio megafono" },
  share: { Icon: FaShareNodes, group: "General", keywords: "compartir" },
  rss: { Icon: FaRss, group: "General", keywords: "feed" },
  qrcode: { Icon: FaQrcode, group: "General", keywords: "qr codigo" },
  info: { Icon: FaCircleInfo, group: "General", keywords: "informacion" },
  question: { Icon: FaCircleQuestion, group: "General", keywords: "faq ayuda" },
  gear: { Icon: FaGear, group: "General", keywords: "config ajustes" },
  lock: { Icon: FaLock, group: "General", keywords: "candado privado" },
  key: { Icon: FaKey, group: "General", keywords: "llave clave" },
  database: { Icon: FaDatabase, group: "General", keywords: "datos db" },
  server: { Icon: FaServer, group: "General", keywords: "servidor" },
  cloud: { Icon: FaCloud, group: "General", keywords: "nube" },
  terminal: { Icon: FaTerminal, group: "General", keywords: "consola shell" },
  code: { Icon: FaCode, group: "General", keywords: "codigo dev" },
  laptop: { Icon: FaLaptop, group: "General", keywords: "computadora pc" },
  mobile: { Icon: FaMobile, group: "General", keywords: "celular telefono app" },
  camera: { Icon: FaCamera, group: "General", keywords: "foto" },
  image: { Icon: FaImage, group: "General", keywords: "foto imagen galeria" },
  palette: { Icon: FaPalette, group: "General", keywords: "arte diseño color" },
  film: { Icon: FaFilm, group: "General", keywords: "cine pelicula" },
  video: { Icon: FaVideo, group: "General", keywords: "camara grabar" },
  tv: { Icon: FaTv, group: "General", keywords: "television" },
  radio: { Icon: FaRadio, group: "General", keywords: "am fm" },
  music: { Icon: FaMusic, group: "General", keywords: "musica cancion" },
  headphones: { Icon: FaHeadphones, group: "General", keywords: "auriculares" },
  guitar: { Icon: FaGuitar, group: "General", keywords: "guitarra" },
  drum: { Icon: FaDrum, group: "General", keywords: "bateria tambor" },
  microphone: { Icon: FaMicrophone, group: "General", keywords: "mic microfono" },
  podcast: { Icon: FaPodcast, group: "General", keywords: "audio" },
  gamepad: { Icon: FaGamepad, group: "General", keywords: "juego gaming control" },
  chess: { Icon: FaChess, group: "General", keywords: "ajedrez" },
  dice: { Icon: FaDice, group: "General", keywords: "dado azar" },
  basketball: { Icon: FaBasketball, group: "General", keywords: "basquet" },
  football: { Icon: FaFutbol, group: "General", keywords: "futbol soccer pelota" },
  dumbbell: { Icon: FaDumbbell, group: "General", keywords: "gym pesas" },
  coffee: { Icon: FaMugHot, group: "General", keywords: "cafe mate taza" },
  utensils: { Icon: FaUtensils, group: "General", keywords: "comida restaurante" },
  plane: { Icon: FaPlane, group: "General", keywords: "viaje avion" },

  // Social
  github: { Icon: FaGithub, group: "Social", keywords: "code repo git" },
  instagram: { Icon: FaInstagram, group: "Social", keywords: "ig insta" },
  linkedin: { Icon: FaLinkedinIn, group: "Social", keywords: "work trabajo" },
  twitter: { Icon: FaXTwitter, group: "Social", keywords: "x tweet" },
  bluesky: { Icon: SiBluesky, group: "Social", keywords: "bsky" },
  threads: { Icon: FaThreads, group: "Social", keywords: "meta" },
  mastodon: { Icon: FaMastodon, group: "Social", keywords: "fediverse" },
  facebook: { Icon: FaFacebookF, group: "Social", keywords: "fb meta" },
  whatsapp: { Icon: FaWhatsapp, group: "Social", keywords: "wa chat mensaje" },
  telegram: { Icon: FaTelegram, group: "Social", keywords: "tg chat" },
  signal: { Icon: SiSignal, group: "Social", keywords: "chat privado" },
  discord: { Icon: FaDiscord, group: "Social", keywords: "chat server" },
  reddit: { Icon: FaReddit, group: "Social", keywords: "foro" },
  snapchat: { Icon: FaSnapchat, group: "Social", keywords: "snap" },
  pinterest: { Icon: FaPinterest, group: "Social", keywords: "pin" },
  tumblr: { Icon: FaTumblr, group: "Social" },
  vk: { Icon: SiVk, group: "Social", keywords: "vkontakte" },
  line: { Icon: SiLine, group: "Social", keywords: "chat" },
  wechat: { Icon: SiWechat, group: "Social", keywords: "weixin chat" },
  linktree: { Icon: SiLinktree, group: "Social", keywords: "bio links" },

  // Video & audio
  youtube: { Icon: FaYoutube, group: "Video & audio", keywords: "yt video" },
  tiktok: { Icon: FaTiktok, group: "Video & audio", keywords: "tt video" },
  twitch: { Icon: FaTwitch, group: "Video & audio", keywords: "stream directo" },
  vimeo: { Icon: FaVimeo, group: "Video & audio", keywords: "video" },
  rumble: { Icon: SiRumble, group: "Video & audio", keywords: "video" },
  bilibili: { Icon: SiBilibili, group: "Video & audio", keywords: "video" },
  spotify: { Icon: FaSpotify, group: "Video & audio", keywords: "musica playlist" },
  soundcloud: { Icon: FaSoundcloud, group: "Video & audio", keywords: "musica audio" },
  bandcamp: { Icon: SiBandcamp, group: "Video & audio", keywords: "musica" },
  tidal: { Icon: SiTidal, group: "Video & audio", keywords: "musica" },
  audible: { Icon: SiAudible, group: "Video & audio", keywords: "audiolibro" },
  pandora: { Icon: SiPandora, group: "Video & audio", keywords: "musica radio" },
  lastfm: { Icon: SiLastdotfm, group: "Video & audio", keywords: "musica scrobble" },
  genius: { Icon: SiGenius, group: "Video & audio", keywords: "letras lyrics" },
  flickr: { Icon: FaFlickr, group: "Video & audio", keywords: "fotos" },
  unsplash: { Icon: SiUnsplash, group: "Video & audio", keywords: "fotos stock" },

  // Writing
  medium: { Icon: FaMedium, group: "Writing", keywords: "blog articulo" },
  substack: { Icon: SiSubstack, group: "Writing", keywords: "newsletter blog" },
  hashnode: { Icon: SiHashnode, group: "Writing", keywords: "blog dev" },
  devto: { Icon: FaDev, group: "Writing", keywords: "dev.to blog" },
  "ghost-blog": { Icon: SiGhost, group: "Writing", keywords: "blog cms" },
  wordpress: { Icon: FaWordpress, group: "Writing", keywords: "blog cms wp" },
  notion: { Icon: SiNotion, group: "Writing", keywords: "notas docs" },
  obsidian: { Icon: SiObsidian, group: "Writing", keywords: "notas" },
  goodreads: { Icon: SiGoodreads, group: "Writing", keywords: "libros" },
  letterboxd: { Icon: SiLetterboxd, group: "Writing", keywords: "peliculas cine" },

  // Dev
  gitlab: { Icon: FaGitlab, group: "Dev", keywords: "git repo" },
  bitbucket: { Icon: FaBitbucket, group: "Dev", keywords: "git repo" },
  stackoverflow: { Icon: FaStackOverflow, group: "Dev", keywords: "so preguntas" },
  codepen: { Icon: SiCodepen, group: "Dev", keywords: "demo frontend" },
  replit: { Icon: SiReplit, group: "Dev", keywords: "ide" },
  leetcode: { Icon: SiLeetcode, group: "Dev", keywords: "algoritmos" },
  codewars: { Icon: SiCodewars, group: "Dev", keywords: "kata" },
  freecodecamp: { Icon: SiFreecodecamp, group: "Dev", keywords: "cursos" },
  kaggle: { Icon: SiKaggle, group: "Dev", keywords: "data ml" },
  huggingface: { Icon: SiHuggingface, group: "Dev", keywords: "ai ml modelos" },
  docker: { Icon: FaDocker, group: "Dev", keywords: "container" },
  npm: { Icon: FaNpm, group: "Dev", keywords: "paquete node" },
  python: { Icon: FaPython, group: "Dev", keywords: "py" },
  javascript: { Icon: FaJs, group: "Dev", keywords: "js" },
  react: { Icon: FaReact, group: "Dev", keywords: "frontend" },
  nodejs: { Icon: FaNodeJs, group: "Dev", keywords: "node backend" },
  aws: { Icon: FaAws, group: "Dev", keywords: "cloud amazon" },
  vercel: { Icon: SiVercel, group: "Dev", keywords: "deploy hosting" },
  netlify: { Icon: SiNetlify, group: "Dev", keywords: "deploy hosting" },
  jira: { Icon: SiJira, group: "Dev", keywords: "tickets" },
  slack: { Icon: FaSlack, group: "Dev", keywords: "chat work" },
  trello: { Icon: FaTrello, group: "Dev", keywords: "kanban tareas" },
  loom: { Icon: SiLoom, group: "Dev", keywords: "video screen" },
  zoom: { Icon: SiZoom, group: "Dev", keywords: "meet videollamada" },

  // Design
  dribbble: { Icon: FaDribbble, group: "Design", keywords: "diseño portfolio" },
  behance: { Icon: FaBehance, group: "Design", keywords: "diseño portfolio" },
  figma: { Icon: FaFigma, group: "Design", keywords: "diseño ui" },
  canva: { Icon: SiCanva, group: "Design", keywords: "diseño" },
  framer: { Icon: SiFramer, group: "Design", keywords: "diseño web" },
  webflow: { Icon: SiWebflow, group: "Design", keywords: "web builder" },
  artstation: { Icon: SiArtstation, group: "Design", keywords: "arte 3d" },
  deviantart: { Icon: SiDeviantart, group: "Design", keywords: "arte" },
  squarespace: { Icon: FaSquarespace, group: "Design", keywords: "web builder" },

  // Money
  patreon: { Icon: FaPatreon, group: "Money", keywords: "apoyo suscripcion" },
  buymeacoffee: { Icon: SiBuymeacoffee, group: "Money", keywords: "cafe donar propina" },
  kofi: { Icon: SiKofi, group: "Money", keywords: "donar propina" },
  gumroad: { Icon: SiGumroad, group: "Money", keywords: "vender producto" },
  paypal: { Icon: FaPaypal, group: "Money", keywords: "pago donar" },
  venmo: { Icon: SiVenmo, group: "Money", keywords: "pago" },
  cashapp: { Icon: SiCashapp, group: "Money", keywords: "pago" },
  kickstarter: { Icon: FaKickstarter, group: "Money", keywords: "crowdfunding" },
  producthunt: { Icon: SiProducthunt, group: "Money", keywords: "launch startup" },
  indiehackers: { Icon: SiIndiehackers, group: "Money", keywords: "startup" },
  etsy: { Icon: FaEtsy, group: "Money", keywords: "tienda vender" },
  shopify: { Icon: FaShopify, group: "Money", keywords: "tienda ecommerce" },
  amazon: { Icon: FaAmazon, group: "Money", keywords: "tienda" },
  calendly: { Icon: SiCalendly, group: "Money", keywords: "agenda reunion cita" },
  coursera: { Icon: SiCoursera, group: "Money", keywords: "curso" },
  udemy: { Icon: SiUdemy, group: "Money", keywords: "curso" },
  scholar: { Icon: SiGooglescholar, group: "Money", keywords: "papers academico" },
  duolingo: { Icon: SiDuolingo, group: "Money", keywords: "idiomas" },
  strava: { Icon: SiStrava, group: "Money", keywords: "correr running deporte" },

  // Gaming
  steam: { Icon: FaSteam, group: "Gaming", keywords: "juegos pc" },
  itch: { Icon: FaItchIo, group: "Gaming", keywords: "indie juegos" },
  unity: { Icon: FaUnity, group: "Gaming", keywords: "motor juegos" },
  roblox: { Icon: SiRoblox, group: "Gaming", keywords: "juegos" },
  epicgames: { Icon: SiEpicgames, group: "Gaming", keywords: "fortnite juegos" },
  playstation: { Icon: SiPlaystation, group: "Gaming", keywords: "ps sony" },
  nintendo: { Icon: SiNintendoswitch, group: "Gaming", keywords: "switch" },
  chesscom: { Icon: SiChessdotcom, group: "Gaming", keywords: "ajedrez" },
  lichess: { Icon: SiLichess, group: "Gaming", keywords: "ajedrez" },
  apple: { Icon: FaApple, group: "Gaming", keywords: "ios mac" },
  google: { Icon: FaGoogle, group: "Gaming", keywords: "buscar" },
  android: { Icon: FaAndroid, group: "Gaming", keywords: "app movil" },
  "google-play": { Icon: FaGooglePlay, group: "Gaming", keywords: "app android" },
  "app-store": { Icon: FaAppStoreIos, group: "Gaming", keywords: "app ios" },
  bitcoin: { Icon: FaBitcoin, group: "Gaming", keywords: "btc crypto" },
  ethereum: { Icon: FaEthereum, group: "Gaming", keywords: "eth crypto web3" },
};

/** Convenience map for rendering. */
export const ICONS = Object.fromEntries(
  Object.entries(ICON_META).map(([name, meta]) => [name, meta.Icon]),
) as Record<LinkIcon, IconType>;
