/**
 * Every icon id you can pick in /admin/config.
 *
 * This is the source of truth for icon *names*. The actual components live in
 * ./icons.tsx, typed as Record<LinkIcon, ...> — so if a name here has no
 * component there (or vice versa), the build fails instead of shipping a
 * broken picker.
 *
 * Names are stored in your saved config, so renaming one orphans any link
 * already using it. Add freely; rename with care.
 *
 * Kept separate from icons.tsx (which pulls in react-icons) so server-side
 * validation can check names without bundling ~250 icon components.
 */
export const ICON_NAMES = [
  // General
  "link",
  "globe",
  "cv",
  "email",
  "at",
  "paper-plane",
  "inbox",
  "phone",
  "calendar",
  "clock",
  "download",
  "file",
  "book",
  "bookmark",
  "newspaper",
  "pen",
  "rocket",
  "chart",
  "chart-pie",
  "store",
  "cart",
  "money",
  "credit-card",
  "wallet",
  "tag",
  "gift",
  "heart",
  "star",
  "thumbs-up",
  "crown",
  "gem",
  "medal",
  "trophy",
  "handshake",
  "lightbulb",
  "bolt",
  "fire",
  "leaf",
  "mountain",
  "compass",
  "anchor",
  "feather",
  "ghost",
  "robot",
  "brain",
  "flask",
  "atom",
  "microscope",
  "calculator",
  "puzzle",
  "map",
  "location",
  "house",
  "building",
  "briefcase",
  "graduation",
  "user",
  "comments",
  "bullhorn",
  "share",
  "rss",
  "qrcode",
  "info",
  "question",
  "gear",
  "lock",
  "key",
  "database",
  "server",
  "cloud",
  "terminal",
  "code",
  "laptop",
  "mobile",
  "camera",
  "image",
  "palette",
  "film",
  "video",
  "tv",
  "radio",
  "music",
  "headphones",
  "guitar",
  "drum",
  "microphone",
  "podcast",
  "gamepad",
  "chess",
  "dice",
  "basketball",
  "football",
  "dumbbell",
  "coffee",
  "utensils",
  "plane",
  // Social
  "github",
  "instagram",
  "linkedin",
  "twitter",
  "bluesky",
  "threads",
  "mastodon",
  "facebook",
  "whatsapp",
  "telegram",
  "signal",
  "discord",
  "reddit",
  "snapchat",
  "pinterest",
  "tumblr",
  "vk",
  "line",
  "wechat",
  "linktree",
  // Video & audio
  "youtube",
  "tiktok",
  "twitch",
  "vimeo",
  "rumble",
  "bilibili",
  "spotify",
  "soundcloud",
  "bandcamp",
  "tidal",
  "audible",
  "pandora",
  "lastfm",
  "genius",
  "flickr",
  "unsplash",
  // Writing
  "medium",
  "substack",
  "hashnode",
  "devto",
  "ghost-blog",
  "wordpress",
  "notion",
  "obsidian",
  "goodreads",
  "letterboxd",
  // Dev
  "gitlab",
  "bitbucket",
  "stackoverflow",
  "codepen",
  "replit",
  "leetcode",
  "codewars",
  "freecodecamp",
  "kaggle",
  "huggingface",
  "docker",
  "npm",
  "python",
  "javascript",
  "react",
  "nodejs",
  "aws",
  "vercel",
  "netlify",
  "jira",
  "slack",
  "trello",
  "loom",
  "zoom",
  // Design
  "dribbble",
  "behance",
  "figma",
  "canva",
  "framer",
  "webflow",
  "artstation",
  "deviantart",
  "squarespace",
  // Money & work
  "patreon",
  "buymeacoffee",
  "kofi",
  "gumroad",
  "paypal",
  "venmo",
  "cashapp",
  "kickstarter",
  "producthunt",
  "indiehackers",
  "etsy",
  "shopify",
  "amazon",
  "calendly",
  "coursera",
  "udemy",
  "scholar",
  "duolingo",
  "strava",
  // Gaming & platforms
  "steam",
  "itch",
  "unity",
  "roblox",
  "epicgames",
  "playstation",
  "nintendo",
  "chesscom",
  "lichess",
  "apple",
  "google",
  "android",
  "google-play",
  "app-store",
  "bitcoin",
  "ethereum",
] as const;

export type LinkIcon = (typeof ICON_NAMES)[number];

export const isLinkIcon = (value: string): value is LinkIcon =>
  (ICON_NAMES as readonly string[]).includes(value);
